#pragma once
#include "Layout/layout_reference.h"

/* Existing editor API names forward to the UI-free layout reference contract. */
#define EditorReferenceKind LayoutReferenceKind
#define EditorGeometricReference LayoutGeometricReference
#define EditorMeasurementStatus LayoutMeasurementStatus
#define EditorResolvedReference LayoutResolvedReference
#define EditorMeasurementKind LayoutMeasurementKind
#define EditorMeasurementResult LayoutMeasurementResult
#define Editor_ResolveReference Layout_ResolveReference
#define Editor_Measure Layout_Measure
#define Editor_MeasurementStatusLabel Layout_MeasurementStatusLabel
#define EDITOR_MEASUREMENT_DEGENERATE LAYOUT_MEASUREMENT_DEGENERATE
#define EDITOR_MEASUREMENT_INVALID LAYOUT_MEASUREMENT_INVALID
#define EDITOR_MEASUREMENT_OK LAYOUT_MEASUREMENT_OK
#define EDITOR_MEASUREMENT_UNRESOLVED LAYOUT_MEASUREMENT_UNRESOLVED
#define EDITOR_MEASUREMENT_UNSUPPORTED LAYOUT_MEASUREMENT_UNSUPPORTED
#define EDITOR_MEASURE_DIRECTION_ANGLE LAYOUT_MEASURE_DIRECTION_ANGLE
#define EDITOR_MEASURE_PARALLEL_PLANE_GAP LAYOUT_MEASURE_PARALLEL_PLANE_GAP
#define EDITOR_MEASURE_PLANAR_ANGLE LAYOUT_MEASURE_PLANAR_ANGLE
#define EDITOR_MEASURE_POINT_DISTANCE LAYOUT_MEASURE_POINT_DISTANCE
#define EDITOR_MEASURE_PROJECTED_DISTANCE LAYOUT_MEASURE_PROJECTED_DISTANCE
#define EDITOR_REFERENCE_AXIS_N LAYOUT_REFERENCE_AXIS_N
#define EDITOR_REFERENCE_AXIS_U LAYOUT_REFERENCE_AXIS_U
#define EDITOR_REFERENCE_AXIS_V LAYOUT_REFERENCE_AXIS_V
#define EDITOR_REFERENCE_FACE LAYOUT_REFERENCE_FACE
#define EDITOR_REFERENCE_ORIGIN LAYOUT_REFERENCE_ORIGIN
