#pragma once
#include "UI/ui_panel.h"
enum {
    UI_FURNITURE_OPEN = 1, UI_FURNITURE_LENGTH, UI_FURNITURE_DEPTH, UI_FURNITURE_HEIGHT,
    UI_FURNITURE_KEEP, UI_FURNITURE_PANELS, UI_FURNITURE_CASE, UI_FURNITURE_BACK,
    UI_FURNITURE_DOOR, UI_FURNITURE_WORKTOP, UI_FURNITURE_APPLY, UI_FURNITURE_CANCEL,
    UI_FURNITURE_CONNECTIONS, UI_FURNITURE_LINK, UI_FURNITURE_DRIVER, UI_FURNITURE_DRIVER_END,
    UI_FURNITURE_FOLLOWER, UI_FURNITURE_FOLLOWER_END, UI_FURNITURE_BEHAVIOR, UI_FURNITURE_ENABLED,
    UI_FURNITURE_GAP, UI_FURNITURE_SAVE_LINK, UI_FURNITURE_REMOVE_LINK, UI_FURNITURE_NEW_LINK,
    UI_FURNITURE_SINK, UI_FURNITURE_SINK_WIDTH, UI_FURNITURE_SINK_LENGTH,
    UI_FURNITURE_SINK_DEPTH, UI_FURNITURE_SINK_WALL_OFFSET, UI_FURNITURE_SINK_FRONT_OFFSET,
    UI_FURNITURE_OVERHANG_WALL, UI_FURNITURE_OVERHANG_AISLE, UI_FURNITURE_OVERHANG_REAR,
    UI_FURNITURE_OVERHANG_FRONT, UI_FURNITURE_SHELF
};
int UIPanel_FurnitureHeight(void);
bool UIPanel_FurnitureEditing(void);
void UIPanel_FurnitureReset(void);
void UIPanel_RenderFurniture(SDL_Renderer* renderer);
bool UIPanel_FurnitureClick(int x, int y);
bool UIPanel_FurnitureEvent(const SDL_Event* event);
bool UIPanel_FurnitureControlRect(int action, SDL_Rect* rect);
