#pragma once

#include "UI/ui_panel.h"

bool UIPanel_SceneAuthoringInspectorHasSelection(void);
int UIPanel_SceneAuthoringInspectorReservedHeight(const UIPanelState* ui);
int UIPanel_SceneAuthoringInspectorDetailsHeight(const UIPanelState* ui);
void Render_UIPanelSceneAuthoringInspector(const UIPanelState* ui, SDL_Renderer* renderer);

bool UIPanel_ToggleSceneAuthoringEditMode(void);
bool UIPanel_ToggleSelectedSceneAuthoringLightEnabled(void);
bool UIPanel_CycleSelectedSceneAuthoringLightKind(void);
bool UIPanel_CycleSelectedSceneAuthoringLightPath(void);
bool UIPanel_CycleSelectedSceneAuthoringCameraPathKind(void);
bool UIPanel_CycleSelectedSceneAuthoringTangentMode(void);
bool UIPanel_CycleSelectedSceneAuthoringCameraOrientation(void);
bool UIPanel_CycleSelectedSceneAuthoringCameraRoll(void);
bool UIPanel_CycleSelectedSceneAuthoringCameraFov(void);
bool UIPanel_CycleSelectedSceneAuthoringCameraClip(void);
bool UIPanel_CycleSelectedSceneAuthoringLightPositionMode(void);
bool UIPanel_CycleSelectedSceneAuthoringLightColor(void);
bool UIPanel_CycleSelectedSceneAuthoringLightIntensity(void);
bool UIPanel_CycleSelectedSceneAuthoringLightSize(void);
bool UIPanel_CycleSelectedSceneAuthoringLightCone(void);
bool UIPanel_CycleSelectedSceneAuthoringLightFalloff(void);
bool UIPanel_CycleSelectedSceneAuthoringMaterialColor(void);
bool UIPanel_ToggleSelectedSceneAuthoringPathPlayback(void);
bool UIPanel_AdvanceSelectedSceneAuthoringPathScrub(void);
bool UIPanel_CycleSelectedSceneAuthoringPathPlaybackMode(void);
bool UIPanel_CycleSelectedSceneAuthoringPathDuration(void);
bool UIPanel_ToggleSelectedSceneAuthoringPathClosed(void);
