#pragma once
#include "UI/ui_panel.h"
typedef enum {
    ROUTES_SELECT=1, ROUTES_NEW, ROUTES_NAME, ROUTES_CABLE, ROUTES_PIPE,
    ROUTES_ENDPOINTS, ROUTES_SOURCE, ROUTES_DESTINATION, ROUTES_USE_SOURCE, ROUTES_USE_DESTINATION,
    ROUTES_PREVIOUS, ROUTES_NEXT, ROUTES_X, ROUTES_Y, ROUTES_Z, ROUTES_INSERT,
    ROUTES_DELETE_POINT, ROUTES_EARLIER, ROUTES_LATER, ROUTES_PICK,
    ROUTES_REFRESH, ROUTES_SAVE, ROUTES_CANCEL, ROUTES_REMOVE, ROUTES_CONFIRM_REMOVE,
    ROUTES_CORRIDORS=100, ROUTES_CORRIDOR_CHOOSER, ROUTES_MARK_CORRIDOR,
    ROUTES_ELECTRICAL, ROUTES_CLASS, ROUTES_COPPER, ROUTES_CIRCUIT, ROUTES_DOMAIN,
    ROUTES_CHECKS, ROUTES_RUN_CHECKS, ROUTES_SHOW,
    ROUTES_RADIUS=120, ROUTES_CLEARANCE, ROUTES_MAX_LENGTH, ROUTES_VOLTS, ROUTES_AMPS,
    ROUTES_AREA, ROUTES_RETURN, ROUTES_ALLOWANCE, ROUTES_FUSE, ROUTES_AWG,
    ROUTES_CHOICE_BASE=1000, ROUTES_CHECK_BASE=2000
} UIPanelRoutesAction;
void UIPanel_LayoutRoutes(void);
void UIPanel_RenderRoutes(SDL_Renderer* renderer);
void UIPanel_RenderRouteViewport(SDL_Renderer* renderer);
void UIPanel_RoutesStopInput(void);
bool UIPanel_RoutesEvent(const SDL_Event* event);
bool UIPanel_RoutesControlRect(int action, SDL_Rect* rect);
