#pragma once
#include "UI/ui_panel.h"

typedef enum {
    PARTS_OBJECTS=1, PARTS_ASSEMBLIES, PARTS_FILTERS, PARTS_LINKS, PARTS_SELECT, PARTS_VOLUMES=7, PARTS_CHECKS,
    PARTS_VIEW_DEFAULTS=200, PARTS_VIEW_NAME, PARTS_VIEW_SAVE, PARTS_CUSTOM_FILTER,
    PARTS_NAME=10, PARTS_TYPE, PARTS_ROLE, PARTS_PARENT, PARTS_SAVE, PARTS_NEW,
    PARTS_PROPERTIES, PARTS_KEY, PARTS_VALUE, PARTS_PROPERTY_KIND, PARTS_SET_PROPERTY,
    PARTS_REMOVE_PROPERTY, PARTS_MOVE, PARTS_DX, PARTS_DY, PARTS_DZ, PARTS_ANGLE,
    PARTS_AXIS, PARTS_APPLY_MOVE, PARTS_DELETE, PARTS_CONFIRM_DELETE, PARTS_CANCEL,
    PARTS_CLEAR_FILTER, PARTS_APPLY_FILTER, PARTS_ADD_SELECTED,
    PARTS_LINK_SOURCE, PARTS_LINK_TARGET, PARTS_LINK_TYPE, PARTS_LINK_SAVE,
    PARTS_LINK_NEW, PARTS_LINK_REMOVE, PARTS_LINK_CONFIRM_REMOVE, PARTS_LINK_CANCEL,
    PARTS_VOLUME_NAME=100, PARTS_VOLUME_W, PARTS_VOLUME_H, PARTS_VOLUME_D,
    PARTS_VOLUME_X, PARTS_VOLUME_Y, PARTS_VOLUME_Z,
    PARTS_VOLUME_SELECT, PARTS_VOLUME_ROLE, PARTS_VOLUME_OWNER, PARTS_VOLUME_POSITION,
    PARTS_VOLUME_SAVE, PARTS_VOLUME_NEW, PARTS_VOLUME_REMOVE, PARTS_VOLUME_CONFIRM_REMOVE,
    PARTS_SPATIAL_CANCEL, PARTS_CHECK_RUN, PARTS_CHECK_RULES, PARTS_CHECK_SOURCE,
    PARTS_CHECK_TARGET, PARTS_CHECK_KIND, PARTS_CHECK_DISTANCE, PARTS_CHECK_SAVE,
    PARTS_CHECK_NEW, PARTS_CHECK_REMOVE, PARTS_CHECK_CONFIRM_REMOVE, PARTS_CHECK_SELECT_A, PARTS_CHECK_SELECT_B, PARTS_ENVELOPE_REGENERATE, PARTS_ENVELOPE_MOVEMENT, PARTS_ENVELOPE_CHECK, PARTS_MOTION_INSPECT, PARTS_MOTION_PREVIOUS, PARTS_MOTION_NEXT, PARTS_MOTION_CLOSE, PARTS_MOTION_RANGE, PARTS_SAVED_MOTION
} UIPanelPartsAction;
void UIPanel_LayoutParts(void);
void UIPanel_RenderParts(SDL_Renderer* renderer);
bool UIPanel_PartsClick(int x, int y);
bool UIPanel_PartsEvent(const SDL_Event* event);
void UIPanel_PartsStopInput(void);
bool UIPanel_PartsControlRect(int action, SDL_Rect* rect);

bool UIPanel_PartsSelectEntity(const char* id);
