CLANG_CC ?= cc
FISICS_BIN ?= ../fisiCs/fisics
FISICS_OVERLAY ?= physics-units
FISICS_ENV ?= FISICS_MAX_PROCS=0
BUILD_TOOLCHAIN ?= clang
PACKAGE_TOOLCHAIN ?= $(BUILD_TOOLCHAIN)
CC := $(CLANG_CC)
ifeq ($(BUILD_TOOLCHAIN),fisics)
CC := $(FISICS_ENV) $(FISICS_BIN) --overlay=$(FISICS_OVERLAY)
endif
PKG_CONFIG ?= pkg-config
DEBUG ?= 0

PACKAGE_APP_NAME := sCulpt.app
PACKAGE_APP_ICON_NAME := AppIcon
PACKAGE_APP_ICON_FILE := $(PACKAGE_APP_ICON_NAME).icns
PACKAGE_ADHOC_SIGN_IDENTITY ?= -

RELEASE_VERSION_FILE ?= VERSION
RELEASE_VERSION ?= $(strip $(shell cat "$(RELEASE_VERSION_FILE)" 2>/dev/null))
ifeq ($(RELEASE_VERSION),)
RELEASE_VERSION := 0.1.0
endif
RELEASE_CHANNEL ?= stable
RELEASE_PRODUCT_NAME := sCulpt
RELEASE_PROGRAM_KEY := line_drawing
RELEASE_BUNDLE_ID := com.cosm.sculpt
RELEASE_CODESIGN_IDENTITY ?= $(if $(strip $(APPLE_SIGN_IDENTITY)),$(APPLE_SIGN_IDENTITY),$(PACKAGE_ADHOC_SIGN_IDENTITY))
APPLE_SIGN_IDENTITY ?=
APPLE_NOTARY_PROFILE ?=
APPLE_TEAM_ID ?=
STAPLE_MAX_ATTEMPTS ?= 6
STAPLE_RETRY_DELAY_SEC ?= 15

ifneq ($(filter $(PACKAGE_TOOLCHAIN),clang fisics),$(PACKAGE_TOOLCHAIN))
$(error Unsupported PACKAGE_TOOLCHAIN '$(PACKAGE_TOOLCHAIN)'; expected clang or fisics)
endif

define program_bin_for
$(BUILD_DIR)/toolchains/$(1)/bin/LineDrawing
endef

.DEFAULT_GOAL := all
