LINE_DRAWING_VK_RUNTIME_VERSION := unavailable

APP_CFLAGS += -DLINE_DRAWING_VK_RUNTIME_AVAILABLE=$(VK_RUNTIME_AVAILABLE)
CFLAGS += -DLINE_DRAWING_VK_RUNTIME_AVAILABLE=$(VK_RUNTIME_AVAILABLE)

ifeq ($(VK_RUNTIME_AVAILABLE),1)
LINE_DRAWING_VK_RUNTIME_VERSION := $(strip $(shell sed -n '1p' "$(VK_RUNTIME_DIR)/VERSION"))
BASE_CFLAGS += -I$(VK_RUNTIME_DIR)/include
CFLAGS += -I$(VK_RUNTIME_DIR)/include
APP_CFLAGS += -I$(VK_RUNTIME_DIR)/include \
	-DVK_RUNTIME_BUILD_VERSION=\"$(LINE_DRAWING_VK_RUNTIME_VERSION)\"
endif
