#pragma once

#include "layout.h"
#include <stdbool.h>

#define LAYOUT_JSON_SCHEMA_VERSION 24
#define LAYOUT_JSON_SCHEMA_VERSION_PANEL_OPENINGS 24
#define LAYOUT_JSON_SCHEMA_VERSION_FURNITURE_CONTACTS 23
#define LAYOUT_JSON_SCHEMA_VERSION_FURNITURE 22
#define LAYOUT_JSON_SCHEMA_VERSION_SAVED_VIEWS 21
#define LAYOUT_JSON_SCHEMA_VERSION_ROUTES 20
#define LAYOUT_JSON_SCHEMA_VERSION_MOTION_ENVELOPES 18
#define LAYOUT_JSON_SCHEMA_VERSION_SPATIAL 17
#define LAYOUT_JSON_SCHEMA_VERSION_RELATIONSHIPS 16
#define LAYOUT_JSON_SCHEMA_VERSION_ENGINEERING 15
#define LAYOUT_JSON_SCHEMA_VERSION_ANGULAR_TRAVEL 14
#define LAYOUT_JSON_SCHEMA_VERSION_LINEAR_TRAVEL 13
#define LAYOUT_JSON_SCHEMA_VERSION_REFERENCE_OFFSETS 12
#define LAYOUT_JSON_SCHEMA_VERSION_CONSTRAINTS 11
#define LAYOUT_JSON_SCHEMA_VERSION_PHYSICAL_CONTEXT 10
#define LAYOUT_JSON_SCHEMA_VERSION_Z_ANCHOR 3
#define LAYOUT_JSON_SCHEMA_VERSION_HANDLE_AXIS 4
#define LAYOUT_JSON_SCHEMA_VERSION_SCENE_BOUNDS 5
#define LAYOUT_JSON_SCHEMA_VERSION_CONSTRUCTION_PLANE 6
#define LAYOUT_JSON_SCHEMA_VERSION_OBJECT3D 7
#define LAYOUT_JSON_SCHEMA_VERSION_OBJECT3D_RECT_PRISM 8
#define LAYOUT_JSON_SCHEMA_VERSION_OBJECT3D_MESH_INSTANCE 9
#define LAYOUT_JSON_SCHEMA_VERSION_MIN_SUPPORTED 0

bool Layout_SaveToFile(const Layout* layout, const char* path);
bool Layout_LoadFromFile(Layout* layout, const char* path);
char* Layout_SaveToString(const Layout* layout);
void Layout_FreeString(char* text);
bool Layout_LoadFromString(Layout* layout, const char* jsonData);
